---
name: music_circle
description: A  music social media app
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.7.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  lit_firebase_auth: ^0.2.3
  font_awesome_flutter: ^8.8.1
  google_fonts: any
  animations: ^2.0.0
  auto_size_text: ^2.1.0
  volume_control: ^0.1.5
  flutter_xlider: ^3.4.0
  double_linked_list: ^1.0.8
  curved_navigation_bar: ^1.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
  - lib/Resources/Images/
