class StringsEvent{
  static const states = [
    'Me',
    'Alabama',
    'Alaska',
    'Arizona',
    'Arkansas',
    'California',
    'Colorado',
    'Connecticut',
    'Delaware',
    'Florida',
    'Georgia',
    'Hawaii',
    'Idaho',
    'Kansas',
    'Kentucky',
    'Louisiana',
    'Maine',
    'Maryland',
    'Massachusetts',
    'Michigan',
    'Minnesota',
    'Mississippi',
    'Missouri',
    'Montana',
    'Nebraska',
    'Nevada',
    'New Hampshire',
    'New Jersey',
    'New Mexico',
    'New York',
    'North Carolina',
    'North Dakota',
    'Ohio',
    'Oklahoma',
    'Oregon',
    'Pennsylvania',
    'Rhode Island',
    'South Carolina',
    'South Dakota',
    'Tennessee',
    'Texas',
    'Utah',
    'Vermont',
    'Virginia',
    'Washington',
    'West Virgina',
    'Wisconsin',
    'Wyoming'
  ];
}

class TestString{
  String lyrics = "Life story:\nMama, I knew I was 'bout it\nWay before venue was crowded\nWay before Kevin pulled up with that Reverend\nI told him to level\nGo fuck on the feelings; don't nut on her face\nTrust me, I feel like the man\nTrust me, I feel like the Wop, rock (Fuck am I—yeah)\nYou can depend on the stock, watch\nBitch, I got ten in the pot, crock\nAll of my limits could die, all of y'all niggas\nAll of my limits could die (All of my limits)\nLook at you, timid as fuck, and you holding me up\nAnd I'm trying to be Nicki Minaj (Yeah)\nRich as a bitch in the drop, rich as a bitch (Yeah)\nRich as my bitch on the side\nHo, I got more than you know\nHo, I got ... Look, watch (Fuck is my ...)\nSpill out your soul in the closet, don't question your passion\nWe flipped that reefer 'cause we couldn't be ashing\nThey got me so high that I look like I'm passing\nBitch, don't you know who you asking?\nBitch, have you tutored the pastor?\nI know the root and the master\nI know the coupe was a casket\nI had that bitch looking like all the shit that I write\nAnd that shit was so good that I passed it\nBust that shit straight out the plastic (Yeah, yeah)\nBitch, I ain’t good; bitch, I’m crafty (Yeah, yeah)\nI wanna piss on a rapper\nI just got hookers and Pampers\nNiggas line up when I practice (Awwww, yeah)\nI’m not a savage, I don’t do shit just to do it\nThis going precise as we planned it (Awwww, yeah)\nI'm just a bandit; plus, I'm as sharp as a tack\nOr a guillotine right at your family (Whoa)\nKeep it so candid, knock you like sheets and some candy\nYou down for this shit? Are you Brandy?\nFind a mechanic, tell 'em I pay 'em in fabric\n3500 in traffic\n[Chorus]\nNigga, I'm savvy\nI look more Cuban than Maverick\nThe metal, the tube or the handle (Hey!)\nNigga, I'm savvy'\nWait, hey (Whoa, whoa, whoa, whoa)\nWait, look, nigga, I'm savvyn\nI look more Cuban than Maverick\nThe metal, the tube or the handle (Hey!)\nNigga, I'm savvy, I look more Cuban than Maverick\nThe metal, the tube or the handle (Hey!)\nNigga, I'm swagging\nBitch, I might shoot at your camera\nBitch, I might shoot at your camera\nNigga, what's hatnin'?\nNiggas wan' piss on your grave\nBitch, I might piss on your family\nNigga, what's hatnin'?'\nBitch, I might shoot at your camera\nBitch, I might shoot at your—\nNigga, what's hatnin\'?\nI look more Cuban than Maverick (Hey!)\nThe metal, the tube or the handle (Hey!)\nNigga, I'm savvy";
}